[pytest]
markers =
    catalog: tests for catalog page
    login_guest: tests for login in quest
    add_to_basket: test for user add to basket
    need_review: test for review
pythonpath = .
addopts = -v -rx --tb=line